spring:
  application:
    name: ccs-quaterlyjobs-svc
  main:
      web-application-type: none
  batch:
    jdbc:
      initialize-schema: always

ccs:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    driver-class-name: oracle.jdbc.pool.OracleDataSource
    username: system
    password: password
    initial-pool-size: 5
    min-pool-size: 8
    max-pool-size: 10